const resourceList = [
    {
      resourceId: '24707191',
      resourceName: 'Carbohydrate Compound',
      resourceQuantity: 1000,
      resourceType: 'Food Synthesis',
      resourceSource: 'Hydroponic Farms',
      resourceDescription: 'Base compound for synthesizing various food products.',
    },
    {
      resourceId: '34451243',
      resourceName: 'Hydrogen Fuel',
      resourceQuantity: 5000,
      resourceType: 'Fuel',
      resourceSource: 'On-board Refinery',
      resourceDescription: 'Primary fuel source for the ship’s engines and reactors.',
    },
    {
      resourceId: '27238748',
      resourceName: 'Titanium Alloy',
      resourceQuantity: 200,
      resourceType: 'Manufacturing Material',
      resourceSource: 'Cargo Storage',
      resourceDescription: 'Used in the fabrication of weapon frames and machinery.',
    },
    {
      resourceId: '66958749',
      resourceName: 'Synthetic Fiber',
      resourceQuantity: 800,
      resourceType: 'Textile',
      resourceSource: 'Recycling Unit',
      resourceDescription: 'Versatile material for producing various types of clothing.',
    },
    {
      resourceId: '05158596',
      resourceName: 'Oxygen Tanks',
      resourceQuantity: 100,
      resourceType: 'Life Support',
      resourceSource: 'Atmospheric Processing',
      resourceDescription: 'Reserve oxygen supply for emergency life support.',
    },
    {
        resourceId: '29247164',
      resourceName: 'Carbon Nanotubes',
      resourceQuantity: 300,
      resourceType: 'Manufacturing Material',
      resourceSource: 'Nanofabrication Lab',
      resourceDescription: 'Strong materials for constructing tools and structural components.',
    },
    {
      resourceId: '78101938',
      resourceName: 'Electronic Components',
      resourceQuantity: 5000,
      resourceType: 'Spare Parts',
      resourceSource: 'Electronics Workshop',
      resourceDescription: 'Assorted components for repair and maintenance of ship systems.',
    },
    {
        resourceId: '70899812',
        resourceName: 'Water Recycling Filters',
        resourceQuantity: 50,
        resourceType: 'Life Support',
        resourceSource: 'Water Recycling Unit',
        resourceDescription: 'Filters for purifying and recycling water onboard.',
      },
      {
        resourceId: '70837954',
        resourceName: 'Protein Sequences',
        resourceQuantity: 200,
        resourceType: 'Food Synthesis',
        resourceSource: 'Bioprocessing Lab',
        resourceDescription: 'Genetic sequences for synthesizing various proteins.',
      },
      {
        resourceId: '19747072',
        resourceName: 'Silica Sand',
        resourceQuantity: 1000,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Cargo Storage',
        resourceDescription: 'Raw material for glass production and silicon-based components.',
      },
      {
        resourceId: '39130267',
        resourceName: 'Polymer Resin',
        resourceQuantity: 1500,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Materials Storage',
        resourceDescription: 'Base material for various plastic and composite fabrications.',
      },
      {
        resourceId: '46008516',
        resourceName: 'Aluminum Ingots',
        resourceQuantity: 500,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Cargo Storage',
        resourceDescription: 'Lightweight metal for structural components and machinery.',
      },
      {
        resourceId: '99408502',
        resourceName: 'Agricultural Seeds',
        resourceQuantity: 10000,
        resourceType: 'Agriculture',
        resourceSource: 'Seed Bank',
        resourceDescription: 'Diverse seeds for hydroponic food production.',
      },
      {
        resourceId: "40826285",
        resourceName: 'Medical Supplies Kit',
        resourceQuantity: 200,
        resourceType: 'Medical',
        resourceSource: 'Medical Bay',
        resourceDescription: 'Essential supplies for medical treatments and emergencies.',
      },
      {
        resourceId: "07419220",
        resourceName: 'Graphene Sheets',
        resourceQuantity: 400,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Nanofabrication Lab',
        resourceDescription: 'Advanced material for high-strength applications.',
      },
      {
        resourceId: "07983316",
        resourceName: 'Nuclear Reactor Fuel Rods',
        resourceQuantity: 50,
        resourceType: 'Fuel',
        resourceSource: 'Energy Storage',
        resourceDescription: 'Fuel for the ship’s nuclear reactors.',
      },
      {
        resourceId: "59234999",
        resourceName: 'Bioplastic',
        resourceQuantity: 1000,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Bioprocessing Lab',
        resourceDescription: 'Eco-friendly plastic alternative made from organic biomass.',
      },
      {
        resourceId: "50480999",
        resourceName: 'Antimatter Canisters',
        resourceQuantity: 10,
        resourceType: 'Advanced Fuel',
        resourceSource: 'High-Energy Physics Lab',
        resourceDescription: 'Highly efficient fuel source for advanced propulsion systems.',
      },
      {
        resourceId: "84817673",
        resourceName: 'Rare Earth Elements',
        resourceQuantity: 300,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Cargo Storage',
        resourceDescription: 'Critical components for electronics and specialized equipment.',
      },
      {
        resourceId: "21173664",
        resourceName: 'Cryogenic Sleep Pods',
        resourceQuantity: 100,
        resourceType: 'Life Support',
        resourceSource: 'Habitation Module',
        resourceDescription: 'Supports long-duration travel by putting crew in hibernation.',
      },
      {
        resourceId: "32230545",
        resourceName: 'LED Grow Lights',
        resourceQuantity: 500,
        resourceType: 'Agriculture Equipment',
        resourceSource: 'Hydroponic Farms',
        resourceDescription: 'Energy-efficient lighting for plant growth in hydroponic farms.',
      },
      {
        resourceId: '50586314',
        resourceName: 'Quantum Computers',
        resourceQuantity: 20,
        resourceType: 'Computing',
        resourceSource: 'Computer Lab',
        resourceDescription: 'Advanced computing systems for navigation and research.',
      },
      {
        resourceId: '32707169',
        resourceName: 'Mycelium Biomass',
        resourceQuantity: 800,
        resourceType: 'Biomanufacturing',
        resourceSource: 'Bioprocessing Unit',
        resourceDescription: 'Versatile biological material for food production and biodegradable packaging.',
      },
      {
        resourceId: '99065934',
        resourceName: 'Solid Lubricant',
        resourceQuantity: 400,
        resourceType: 'Maintenance',
        resourceSource: 'Engineering Bay',
        resourceDescription: 'Graphite-based lubricant for machinery maintenance without attracting dust.',
      },
      {
        resourceId: '60383090',
        resourceName: 'Radiation Shielding Material',
        resourceQuantity: 300,
        resourceType: 'Construction',
        resourceSource: 'Cargo Storage',
        resourceDescription: 'Specialized materials for protecting the ship and crew from cosmic radiation.',
      },
      {
        resourceId: '78910059',
        resourceName: 'High-Efficiency Solar Panels',
        resourceQuantity: 100,
        resourceType: 'Energy',
        resourceSource: 'Energy Storage',
        resourceDescription: 'Advanced photovoltaic cells for supplemental power generation from solar energy.',
      },
      {
        resourceId: '37259134',
        resourceName: 'Smart Fabric',
        resourceQuantity: 600,
        resourceType: 'Textile',
        resourceSource: 'Materials Storage',
        resourceDescription: 'Fabric with embedded sensors for health monitoring and adaptive thermal regulation.',
      },
      {
        resourceId: '99480105',
        resourceName: '3D Printer Resin',
        resourceQuantity: 2000,
        resourceType: 'Manufacturing Material',
        resourceSource: 'Manufacturing Lab',
        resourceDescription: 'Resin for 3D printing parts, tools, and other custom items on demand.',
      },
      {
        resourceId: '86108752',
        resourceName: 'Magnetic Levitation Components',
        resourceQuantity: 150,
        resourceType: 'Advanced Manufacturing',
        resourceSource: 'Engineering Bay',
        resourceDescription: 'Parts for creating maglev systems for efficient, wear-free movement.',
      },
      {
        resourceId: '82604595',
        resourceName: 'Electrolysis Equipment',
        resourceQuantity: 50,
        resourceType: 'Water and Oxygen Production',
        resourceSource: 'Life Support Systems',
        resourceDescription: 'Apparatus for splitting water into oxygen and hydrogen for breathable air and fuel.',
      },
      {
        resourceId: '82604595',
        resourceName: 'Vitamin and Mineral Supplements',
        resourceQuantity: 5000,
        resourceType: 'Health',
        resourceSource: 'Medical Bay',
        resourceDescription: 'Supplements to ensure balanced nutrition for the crew under all conditions.',
      },
      {
        resourceId: '16542023',
        resourceName: 'Emergency Ration Packs',
        resourceQuantity: 1000,
        resourceType: 'Food',
        resourceSource: 'Food Storage',
        resourceDescription: 'Compact, high-energy food packs for emergency situations.',
      },
      {
        resourceId: '30278242',
        resourceName: 'Ozone Generator',
        resourceQuantity: 20,
        resourceType: 'Air Purification',
        resourceSource: 'Life Support Systems',
        resourceDescription: 'Device for sterilizing and purifying air to eliminate pathogens and odors.',
      },
      {
        resourceId: '66817507',
        resourceName: 'Virtual Reality Equipment',
        resourceQuantity: 100,
        resourceType: 'Recreation',
        resourceSource: 'Recreational Facility',
        resourceDescription: 'Advanced VR gear for training, education, and entertainment to maintain crew morale.',
      },
      {
        resourceId: '44532882',
        resourceName: 'Waste Recycling Systems',
        resourceQuantity: 50,
        resourceType: 'Sustainability',
        resourceSource: 'Waste Processing Unit',
        resourceDescription: 'Systems for converting waste into reusable materials and compounds.',
      },
      {
        resourceId: '59595250',
        resourceName: 'Inert Gases',
        resourceQuantity: 500,
        resourceType: 'Industrial',
        resourceSource: 'Gas Storage',
        resourceDescription: 'Gases like Argon and Neon for industrial processes and atmospheric control.',
      },
      {
        resourceId: '99534536',
        resourceName: 'Habitat Module Seeds',
        resourceQuantity: 300,
        resourceType: 'Biosphere Management',
        resourceSource: 'Seed Bank',
        resourceDescription: 'Seeds for creating a balanced ecosystem within habitat modules.',
      },
      {
        resourceId: '99534536',
        resourceName: 'Nanostructured Alloys',
        resourceQuantity: 250,
        resourceType: 'Advanced Manufacturing Material',
        resourceSource: 'Metal Fabrication Unit',
        resourceDescription: 'High-strength alloys for critical spacecraft components, offering improved resistance to wear and thermal stress.',
      },
      {
        resourceId: '34690641',
        resourceName: 'Ceramic Composites',
        resourceQuantity: 300,
        resourceType: 'Heat Resistant Material',
        resourceSource: 'Cargo Storage',
        resourceDescription: 'Used in the manufacture of heat shields and high-temperature engine components.',
      },
      {
        resourceId: '65488099',
        resourceName: 'Superconductor Wire',
        resourceQuantity: 200,
        resourceType: 'Electrical',
        resourceSource: 'Electrical Workshop',
        resourceDescription: 'Essential for creating efficient power transmission systems and advanced scientific instruments.',
      },
      {
        resourceId: '25093377',
        resourceName: 'Pharmaceutical Precursors',
        resourceQuantity: 500,
        resourceType: 'Medical',
        resourceSource: 'Medical Bay',
        resourceDescription: 'Raw materials for synthesizing a wide range of pharmaceuticals in the ship\'s medical laboratory.',
      },
      {
        resourceId: '31345718',
        resourceName: 'Bioreactor Cultures',
        resourceQuantity: 400,
        resourceType: 'Biotechnology',
        resourceSource: 'Bioprocessing Lab',
        resourceDescription: 'Cultures used in bioreactors for producing food, medicine, and other biological products.',
      },
      {
        resourceId: '13453589',
        resourceName: 'Liquid Crystal Displays',
        resourceQuantity: 150,
        resourceType: 'Electronics',
        resourceSource: 'Electronics Workshop',
        resourceDescription: 'Components for building and repairing display panels and touchscreens.',
      },
      {
        resourceId: '94657404',
        resourceName: 'Atmospheric Sensors',
        resourceQuantity: 200,
        resourceType: 'Instrumentation',
        resourceSource: 'Sensor Array',
        resourceDescription: 'For monitoring and adjusting the ship\'s internal atmosphere, ensuring optimal living conditions.',
      },
      {
        resourceId: '88713204',
        resourceName: 'Hydrogel Packs',
        resourceQuantity: 1000,
        resourceType: 'Medical',
        resourceSource: 'Medical Bay',
        resourceDescription: 'Used for medical treatments, especially burn care, and as a medium for growing certain types of cells.',
      },
      {
        resourceId: '85235904',
        resourceName: 'Neurostimulator Devices',
        resourceQuantity: 50,
        resourceType: 'Healthcare',
        resourceSource: 'Medical Bay',
        resourceDescription: 'Advanced medical devices for treating neurological disorders and aiding in mental health management.',
      },
      {
        resourceId: '49287381',
        resourceName: 'Artificial Intelligence Cores',
        resourceQuantity: 30,
        resourceType: 'Computing',
        resourceSource: 'Computer Lab',
        resourceDescription: 'The computational heart of AI systems, vital for automated ship operations and decision-making support.',
      },
      {
        resourceId: '20523830',
        resourceName: 'Haptic Feedback Suits',
        resourceQuantity: 100,
        resourceType: 'Training and Simulation',
        resourceSource: 'Training Facility',
        resourceDescription: 'Suits that provide physical feedback for virtual reality environments, enhancing training realism.',
      },
      {
        resourceId: '84172435',
        resourceName: 'Ionic Liquids',
        resourceQuantity: 200,
        resourceType: 'Chemical',
        resourceSource: 'Chemistry Lab',
        resourceDescription: 'Versatile solvents and electrolytes for a wide range of chemical processes and energy storage solutions.',
      },
      {
        resourceId: '68595367',
        resourceName: 'Piezoelectric Crystals',
        resourceQuantity: 300,
        resourceType: 'Material',
        resourceSource: 'Materials Lab',
        resourceDescription: 'Crucial for sensors and actuators, especially in precision machinery and instrumentation.',
      },
      {
        resourceId: '67098129',
        resourceName: 'Spore-Based Fire Suppressants',
        resourceQuantity: 500,
        resourceType: 'Safety',
        resourceSource: 'Safety Equipment Storage',
        resourceDescription: 'Non-toxic, biodegradable fire suppressants for enhancing onboard fire safety without harming the environment.',
      },
      {
        resourceId: '02217880',
        resourceName: 'Thermal Insulation Foam',
        resourceQuantity: 400,
        resourceType: 'Construction Material',
        resourceSource: 'Construction Bay',
        resourceDescription: 'For insulating the hull and internal compartments, maintaining temperature control efficiently.',
      },
      {
        resourceId: '99706311',
        resourceName: 'Optical Fiber Cable',
        resourceQuantity: 1000,
        resourceType: 'Communication',
        resourceSource: 'Communications Bay',
        resourceDescription: 'High-speed data transmission cables for the ship\'s internal communication network and sensor data processing.',
      },
      {
        resourceId: '12857850',
        resourceName: 'Symbiotic Plant Seeds',
        resourceQuantity: 2000,
        resourceType: 'Agriculture',
        resourceSource: 'Seed Bank',
        resourceDescription: 'Seeds for plants that can form symbiotic relationships with human habitats, improving air quality and providing psychological benefits.',
      },
  ];

  export {resourceList};